---
version: 2
# logfile: 'efm-langserver.log'
loglevel: 0

tools:
  make-checkmake: &make-checkmake
    lint-command: 'checkmake'
    lint-stdin: true

  dockerfile-hadolint: &dockerfile-hadolint
    lint-command: 'hadolint'
    lint-formats:
      - '%f:%l %m'

  sh-shellcheck: &sh-shellcheck
    lint-command: 'shellcheck -f gcc -x'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  sh-shfmt: &sh-shfmt
    format-command: 'shfmt -ci -s -bn'
    format-stdin: true

  javascript-eslint: &javascript-eslint
    lint-command: 'npx eslint -f unix --stdin'
    lint-ignore-exit-code: true
    lint-stdin: true

  html-prettier: &html-prettier
    format-command: 'npx prettier --parser html'

  css-prettier: &css-prettier
    format-command: 'npx prettier --parser css'

  json-fixjson: &json-fixjson
    format-command: 'fixjson'

  csv-csvlint: &csv-csvlint
    lint-command: 'csvlint'

  proto-buf: &proto-buf
    lint-command: 'buf check lint --file'

  proto-prototool: &proto-prototool
    lint-command: 'prototool lint'
    format-command: 'prototool format -f -w'

languages:
  make:
    - <<: *make-checkmake

  Dockerfile:
    - <<: *dockerfile-hadolint

  sh:
    - <<: *sh-shellcheck
    - <<: *sh-shfmt
  # 
  # javascript:
  #   - <<: *javascript-eslint
  # 
  # javascriptreact:
  #   - <<: *javascript-eslint
  # 
  # typescript:
  #   - <<: *javascript-eslint
  # 
  # typescriptreact:
  #   - <<: *javascript-eslint

  html:
    - <<: *html-prettier

  css:
    - <<: *css-prettier

  json:
    - <<: *json-fixjson

  csv:
    - <<: *csv-csvlint

  proto:
    - <<: *proto-buf
    - <<: *proto-prototool
