[linters]
disable-all = true
enable = [
  'deadcode',
  'errcheck',
  'gosimple',
  'govet',
  'ineffassign',
  'staticcheck',
  'structcheck',
  'typecheck',
  'unused',
  'varcheck',
  'bodyclose',
  'depguard',
  'dogsled',
  # 'dupl',
  # 'funlen',
  # 'gochecknoglobals',
  # 'gochecknoinits',
  'gocognit',
  'goconst',
  'gocritic',
  'gocyclo',
  # 'godox',
  'gofmt',
  'goimports',
  # 'golint',
  # 'gomnd',
  'goprintffuncname',
  'gosec',
  'interfacer',
  # 'lll',
  # 'maligned',
  'misspell',
  'nakedret',
  'prealloc',
  'rowserrcheck',
  'scopelint',
  # 'stylecheck',
  'unconvert',
  'unparam',
  'whitespace',
  # 'wsl',
]
