[run]
timeout = "5m"
[linters]
enable-all = true
disable = [
  'cyclop',
  'exhaustivestruct',
  'funlen',
  'gochecknoglobals',
  'gocognit',
  'gocyclo',
  'godot',
  'goerr113',
  'golint',
  'gomnd',
  'gosec',
  'interfacer',
  'lll',
  'maligned',
  'nlreturn',
  'revive',
  'scopelint',
  'stylecheck',
  'unparam',
  'wrapcheck',
  'wsl',
]


[issues]
max-issues-per-linter = 0
max-same-issues = 0
