if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zshrc" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zshrc"
fi

#
## aliases
#
alias man='LANG=ja_JP.UTF-8 /usr/bin/man'
alias javac='javac -J-Dfile.encoding=UTF-8'
alias java='java -Dfile.encoding=UTF-8'
eval "$(hub alias -s)"
# ローカルのnode_modulesからの利用
alias npm-exec='PATH=$(npm bin):$PATH'
alias gh='ghq list -p | pe cd'
alias ll='ls -alh'
alias la='ls -a'
alias lf='ls -F'
alias brew-cask-clean-outdated='for c in /opt/homebrew-cask/Caskroom/*; do vl=(`ls -t $c`) && for v in "${vl[@]:1}"; do rm -rf "$c/$v"; done; done'
alias brew-cask-update='for c in `brew cask list`; do ! brew cask info $c | grep -qF "Not installed" || brew cask install $c; done && brew-cask-clean-outdated'

# ローカルの設定ファイルがあればそれを読み込み
if [ -f "$HOME/.zshrc.local" ]; then
  source "$HOME/.zshrc.local"
fi

# rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
