# WezTerm shell integration (OSC 7, OSC 133, semantic zones)
if [[ "$TERM_PROGRAM" == "WezTerm" ]]; then
  source "/Applications/WezTerm.app/Contents/Resources/wezterm.sh"

  # Set tab title to git repo name or directory name
  function _wezterm_set_tab_title() {
    local title
    # Try to get git repo root name
    local git_root
    git_root=$(git rev-parse --show-toplevel 2>/dev/null)
    if [[ -n "$git_root" ]]; then
      title="${git_root:t}"  # basename
    else
      title="${PWD:t}"  # current directory name
    fi
    # OSC 1 sets tab title (only if not explicitly set)
    printf "\e]1;%s\a" "$title"
  }
  add-zsh-hook precmd _wezterm_set_tab_title
fi
