#!/usr/bin/env bash

set -eu

cd "$(dirname "${BASH_SOURCE:-$0}")" || exit

{
	echo "# Auto generated by \"gen_gitignore.sh\". DO NOT EDIT."
	echo ""
	echo ",*"
	echo "*.log"
	echo ".envrc"
	echo "pyvenv.cfg"
	echo ".pyflyby"
	echo ".nvim.lua"
	echo ".nvimrc"
	echo ".exrc"
	echo ".docs"
	echo ""

	echo "# for ripgrep"
	echo ".rgignore"
	echo ""

	echo "# for tmuxinator"
	echo ".tmuxinator.yml"
	echo ""

	echo "# for https://taskfile.dev/"
	echo ".task"
	echo ""

	echo "# for claude code"
  echo ".claude"
	echo "CLAUDE.md"
  echo ".mcp.json"
	echo ""

	# Use [simonwhitaker/gibo: Easy access to gitignore boilerplates](https://github.com/simonwhitaker/gibo).
	gibo dump Dropbox Eclipse JetBrains Linux macOS MicrosoftOffice Vagrant Ninja Tags Vim VisualStudioCode Xcode

  echo ""
  echo "!tags/"
} >gitignore
